Map<String, String> country = {
  'AF': 'Afghanistan',
  'AL': 'Albania',
  'DZ': 'Algeria',
  'AD': 'Andorra',
  'AO': 'Angola',
  'AI': 'Anguilla',
  'AG': 'Antigua and Barbuda',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AW': 'Aruba',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BS': 'Bahamas',
  'BH': 'Bahrain',
  'BD': 'Bangladesh',
  'BB': 'Barbados',
  'BY': 'Belarus',
  'BE': 'Belgium',
  'BZ': 'Belize',
  'BJ': 'Benin',
  'BM': 'Bermuda',
  'BT': 'Bhutan',
  'BO': 'Bolivia',
  'BA': 'Bosnia and Herzegovina',
  'BW': 'Botswana',
  'BR': 'Brazil',
  'VG': 'British Virgin Islands',
  'BN': 'Brunei',
  'BG': 'Bulgaria',
  'BF': 'Burkina Faso',
  'BI': 'Burundi',
  'KH': 'Cambodia',
  'CM': 'Cameroon',
  'CA': 'Canada',
  'CV': 'Cape Verde',
  'KY': 'Cayman Islands',
  'CF': 'Central African Republic',
  'TD': 'Chad',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Colombia',
  'KM': 'Comoros',
  'CG': 'Congo - Brazzaville',
  'CD': 'Congo - Kinshasa',
  'CR': 'Costa Rica',
  'HR': 'Croatia',
  'CU': 'Cuba',
  'CW': 'Curaçao',
  'CY': 'Cyprus',
  'CZ': 'Czechia',
  'CI': 'Côte d\'Ivoire',
  'DK': 'Denmark',
  'DJ': 'Djibouti',
  'DM': 'Dominica',
  'DO': 'Dominican Republic',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'SV': 'El Salvador',
  'GQ': 'Equatorial Guinea',
  'ER': 'Eritrea',
  'EE': 'Estonia',
  'ET': 'Ethiopia',
  'FK': 'Falkland Islands',
  'FO': 'Faroe Islands',
  'FJ': 'Fiji',
  'FI': 'Finland',
  'FR': 'France',
  'GF': 'French Guiana',
  'PF': 'French Polynesia',
  'GA': 'Gabon',
  'GM': 'Gambia',
  'GE': 'Georgia',
  'DE': 'Germany',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GR': 'Greece',
  'GL': 'Greenland',
  'GD': 'Grenada',
  'GP': 'Guadeloupe',
  'GT': 'Guatemala',
  'GG': 'Guernsey',
  'GN': 'Guinea',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HT': 'Haiti',
  'HN': 'Honduras',
  'HK': 'Hong Kong SAR China',
  'HU': 'Hungary',
  'IS': 'Iceland',
  'IN': 'India',
  'ID': 'Indonesia',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'IE': 'Ireland',
  'IM': 'Isle of Man',
  'IL': 'Israel',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JP': 'Japan',
  'JE': 'Jersey',
  'JO': 'Jordan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KI': 'Kiribati',
  'KW': 'Kuwait',
  'KG': 'Kyrgyzstan',
  'LA': 'Laos',
  'LV': 'Latvia',
  'LB': 'Lebanon',
  'LS': 'Lesotho',
  'LR': 'Liberia',
  'LY': 'Libya',
  'LI': 'Liechtenstein',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'MO': 'Macao SAR China',
  'MK': 'Macedonia',
  'MG': 'Madagascar',
  'MW': 'Malawi',
  'MY': 'Malaysia',
  'MV': 'Maldives',
  'ML': 'Mali',
  'MT': 'Malta',
  'MQ': 'Martinique',
  'MR': 'Mauritania',
  'MU': 'Mauritius',
  'YT': 'Mayotte',
  'MX': 'Mexico',
  'MD': 'Moldova',
  'MC': 'Monaco',
  'MN': 'Mongolia',
  'ME': 'Montenegro',
  'MS': 'Montserrat',
  'MA': 'Morocco',
  'MZ': 'Mozambique',
  'MM': 'Myanmar (Burma)',
  'NA': 'Namibia',
  'NR': 'Nauru',
  'NP': 'Nepal',
  'NL': 'Netherlands',
  'NC': 'New Caledonia',
  'NZ': 'New Zealand',
  'NI': 'Nicaragua',
  'NE': 'Niger',
  'NG': 'Nigeria',
  'NU': 'Niue',
  'NF': 'Norfolk Island',
  'KP': 'North Korea',
  'NO': 'Norway',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PS': 'Palestinian Territories',
  'PA': 'Panama',
  'PG': 'Papua New Guinea',
  'PY': 'Paraguay',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PL': 'Poland',
  'PT': 'Portugal',
  'QA': 'Qatar',
  'RE': 'Réunion',
  'RO': 'Romania',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'WS': 'Samoa',
  'SM': 'San Marino',
  'ST': 'São Tomé and Príncipe',
  'SA': 'Saudi Arabia',
  'SN': 'Senegal',
  'RS': 'Serbia',
  'SC': 'Seychelles',
  'SL': 'Sierra Leone',
  'SG': 'Singapore',
  'SX': 'Sint Maarten',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'SB': 'Solomon Islands',
  'SO': 'Somalia',
  'ZA': 'South Africa',
  'KR': 'South Korea',
  'SS': 'South Sudan',
  'ES': 'Spain',
  'LK': 'Sri Lanka',
  'BL': 'St. Barthélemy',
  'SH': 'St. Helena',
  'KN': 'St. Kitts and Nevis',
  'LC': 'St. Lucia',
  'MF': 'St. Martin',
  'PM': 'St. Pierre and Miquelon',
  'VC': 'St. Vincent and Grenadines',
  'SD': 'Sudan',
  'SR': 'Suriname',
  'SJ': 'Svalbard and Jan Mayen',
  'SZ': 'Swaziland',
  'SE': 'Sweden',
  'CH': 'Switzerland',
  'SY': 'Syria',
  'TW': 'Taiwan',
  'TJ': 'Tajikistan',
  'TZ': 'Tanzania',
  'TH': 'Thailand',
  'TL': 'Timor-Leste',
  'TG': 'Togo',
  'TO': 'Tonga',
  'TT': 'Trinidad and Tobago',
  'TN': 'Tunisia',
  'TR': 'Turkey',
  'TM': 'Turkmenistan',
  'TC': 'Turks and Caicos Islands',
  'TV': 'Tuvalu',
  'UG': 'Uganda',
  'UA': 'Ukraine',
  'AE': 'United Arab Emirates',
  'GB': 'United Kingdom',
  'US': 'United States of America',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VU': 'Vanuatu',
  'VA': 'Vatican City',
  'VE': 'Venezuela',
  'VN': 'Vietnam',
  'WF': 'Wallis and Futuna',
  'EH': 'Western Sahara',
  'YE': 'Yemen',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
};

Map<String, String> weatherConditionMap = {
  "Clear": "Clear sky",
  "Rain": "Rainy",
  "Thunderstorm": "Thunderstorm",
  "Drizzle": "Drizzle",
  "Snow": "Snowy",
  "Mist": "Misty",
  "Fog": "Foggy",
  "Smoke": "Smoky",
  "Haze": "Hazy",
  "Dust": "Dusty",
  "Sand": "Sandstorm",
  "Ash": "Ashfall",
  "Squall": "Squally",
  "Tornado": "Tornado",
};

Map<String, String> weatherSuggestions = {
  'clear sky': 'Sunglasses on',
  'few clouds': 'Don\'t stop the fun',
  'scattered clouds': 'Carry sunglasses',
  'broken clouds': 'Clouds trying to break your sunshine? Nah!',
  'overcast clouds': 'Dress warmly',
  'mist': 'Drive carefully!',
  'fog': 'Pretend you\'re in a mystery movie!',
  'light rain': 'Grab an umbrella',
  'moderate rain': 'Grab an umbrella',
  'heavy rain': 'Calm music on',
  'thunderstorm': 'Stay indoors',
  'snow': 'Sweaters suites you',
  'sleet': 'Slippery roads',
  'hail': 'Bring your car inside',
  'showers': 'You might find a rainbow!',
  'rain and snow': 'A weather combo platter!',
  'tornado': 'Seek shelter',
  'hurricane': 'Evacuate if necessary',
  'tropical storm': 'Tie down the trampoline!',
  'sandstorm': 'Stay indoors',
  'dust': 'Wear a mask',
  'smoke': 'BBQ party or just smokin\' views?',
};

Map<String, String> weatherDescriptions = {
  'clear sky': 'Sun\'s out',
  'few clouds': 'Clouds, just visiting.',
  'scattered clouds': 'Cloudy, sun peeking through.',
  'broken clouds': 'Cloudy no rainy.',
  'overcast clouds': 'Gray skies, cozy vibes.',
  'mist': 'Misty world.',
  'fog': 'Foggy scene!',
  'light rain': 'Light rain, dance break!',
  'moderate rain': 'Rain\'s groove, not heavy.',
  'heavy rain': 'Heavy rain, indoor party!',
  'thunderstorm': 'Thunder and lightning show!',
  'snow': 'Snowflakes falling, winter wonder.',
  'sleet': 'Rain and ice mix.',
  'hail': 'Hailstones, icy surprises.',
  'showers': 'Quick rain showers pass.',
  'rain and snow': 'Rain meets snow playtime!',
  'tornado': 'Tornado alert, take cover!',
  'hurricane': 'Hurricane prep time, caution!',
  'tropical storm': 'Tropical storm, winds whirl.',
  'sandstorm': 'Sandstorm, indoor arts day!',
  'dust': 'Dust storm, visibility down.',
  'smoke': 'Smoky skies, BBQ vibes!',
};
