Map<String, String> weatherSuggestions = {
  'clear sky': 'Sunglasses on',
  'few clouds': 'Don\'t stop the fun',
  'scattered clouds': 'Carry sunglasses',
  'broken clouds': 'Clouds trying to break your sunshine? Nah!',
  'overcast clouds': 'Dress warmly',
  'mist': 'Drive carefully!',
  'fog': 'Pretend you\'re in a mystery movie!',
  'light rain': 'Grab an umbrella',
  'moderate rain': 'Grab an umbrella',
  'heavy rain': 'Calm music on',
  'thunderstorm': 'Stay indoors',
  'snow': 'Sweaters suites you',
  'sleet': 'Slippery roads',
  'hail': 'Bring your car inside',
  'showers': 'You might find a rainbow!',
  'rain and snow': 'A weather combo platter!',
  'tornado': 'Seek shelter',
  'hurricane': 'Evacuate if necessary',
  'tropical storm': 'Tie down the trampoline!',
  'sandstorm': 'Stay indoors',
  'dust': 'Wear a mask',
  'smoke': 'BBQ party or just smokin\' views?',
};

Map<String, String> weatherDescriptions = {
  'clear sky': 'Sun\'s out',
  'few clouds': 'Clouds, just visiting.',
  'scattered clouds': 'Cloudy, sun peeking through.',
  'broken clouds': 'Cloudy no rainy.',
  'overcast clouds': 'Gray skies, cozy vibes.',
  'mist': 'Misty world.',
  'fog': 'Foggy scene!',
  'light rain': 'Light rain, dance break!',
  'moderate rain': 'Rain\'s groove, not heavy.',
  'heavy rain': 'Heavy rain, indoor party!',
  'thunderstorm': 'Thunder and lightning show!',
  'snow': 'Snowflakes falling, winter wonder.',
  'sleet': 'Rain and ice mix.',
  'hail': 'Hailstones, icy surprises.',
  'showers': 'Quick rain showers pass.',
  'rain and snow': 'Rain meets snow playtime!',
  'tornado': 'Tornado alert, take cover!',
  'hurricane': 'Hurricane prep time, caution!',
  'tropical storm': 'Tropical storm, winds whirl.',
  'sandstorm': 'Sandstorm, indoor arts day!',
  'dust': 'Dust storm, visibility down.',
  'smoke': 'Smoky skies, BBQ vibes!',
};
